import {  Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Shared/Navbar";
import Footer from "./Components/Shared/Footer";
import AuthProvider from "./services/AuthProvider";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "HungryNaki?",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

<AuthProvider>
      <body className="">
        <nav>
          <Navbar/>
        </nav>
        {children}
     <Footer/>
      </body>
      </AuthProvider>
    </html>
  );
}
